// Generated by CoffeeScript 1.6.3
(function() {
  'Get current weather conditions via forecast.io.\n    ';
  var config, key, loc, params, req, url;

  config = require('config.json');

  params = config.defaults;

  if (!config.key) {
    console.log("Please specify your forecast.io api key in `" + __dirname + "/../config.json`");
    process.exit(1);
  }

  req = require('request');

  key = config.key;

  loc = config.coords;

  url = "https://api.forecast.io/forecast/" + key + "/" + loc;

  exports.forecast = function(callback) {
    return req(url, function(err, res, body) {
      return callback(JSON.parse(body));
    });
  };

  exports.now = function(args) {
    var render;
    if (args == null) {
      args = [];
    }
    'Show current weather conditions via forecast.io.\n\n`args` should be an array of strings indicating parameters \nof interest, e.g. "time", "humidity", etc.\n\nWithout args you get back something like (or whatever \ndefaults you\'ve specified in `config.json`) ...\n\n{ time: 1378231463,\n  summary: \'Clear\',\n  icon: \'clear-day\',\n  precipIntensity: 0,\n  precipProbability: 0,\n  temperature: 82.3,\n  apparentTemperature: 84.07,\n  dewPoint: 64.92,\n  windSpeed: 9.07,\n  windBearing: 357,\n  cloudCover: 0.19,\n  humidity: 0.56,\n  pressure: 1005.71,\n  visibility: 10,\n  ozone: 291.68 }\n';
    render = function(args) {
      if (args.length) {
        params = args;
      }
      return function(err, res, body) {
        var data, p, _i, _len, _results;
        data = JSON.parse(body);
        if (params) {
          _results = [];
          for (_i = 0, _len = params.length; _i < _len; _i++) {
            p = params[_i];
            _results.push(console.log("" + p + ": " + data.currently[p]));
          }
          return _results;
        } else {
          return console.log(data.currently);
        }
      };
    };
    return req(url, render(args));
  };

}).call(this);
